const Node = require('./Node');
const LinkedList = require('./LinkedList');
const HashMap = require('./HashMap');

const myHashMap = new HashMap();
myHashMap.set('Todd', 42);
myHashMap.set('odTd', 41);
myHashMap.set('Diane', 66);

// console.log(myHashMap);
// console.log(myHashMap.get('Diane'));
// console.log(myHashMap.get('diane'));
// console.log(myHashMap.has('Todd'));
// console.log(myHashMap.has('MrPB'));
// console.log(myHashMap.has('todd'));
// console.log(myHashMap.remove('odTd'));
// console.log(myHashMap.remove('tod'));
// console.log(myHashMap.length());
// console.log(myHashMap.clear());
// console.log(myHashMap);
console.log(myHashMap.keys());
console.log(myHashMap.values());
console.log(myHashMap.entries());

myHashMap.set('t', 42);
myHashMap.set('ad', 41);
myHashMap.set('De', 66);
myHashMap.set('Td', 42);
myHashMap.set('osdTd', 41);
myHashMap.set('Diadsfne', 66);
myHashMap.set('Todad', 42);
myHashMap.set('odTssd', 41);
myHashMap.set('Diappasdne', 66);
myHashMap.set('Todeed', 42);
myHashMap.set('odTifind', 41);
myHashMap.set('Dianeeeee', 66);
myHashMap.set('tddsfd', 42);
myHashMap.set('sdfad', 41);
myHashMap.set('Dehgjjg', 66);
myHashMap.set('Thnghngd', 42);
myHashMap.set('osddfgdTd', 41);
myHashMap.set('Diadddddsfne', 66);
myHashMap.set('Togfghgfhdad', 42);
myHashMap.set('odrsTssd', 41);
myHashMap.set('Todeeeeed', 42);
myHashMap.set('odTieeeeefind', 41);
myHashMap.set('Dianeeeeeeeee', 66);
myHashMap.set('tddeeeesfd', 42);
myHashMap.set('sdeeeefad', 41);
myHashMap.set('Deeeeehgjjg', 66);
myHashMap.set('Thngeeeehngd', 42);
myHashMap.set('osddfgeeedTd', 41);
myHashMap.set('Diaddeedddsfne', 66);
myHashMap.set('Togfgeeehgfhdad', 42);
myHashMap.set('qd', 41);
console.log(myHashMap);
